[gdrive]
type = drive
scope = drive
team_drive = 

[drive]
type = drive
client_id = 446077114801-tcg037lcmkpdkb1k9h3gc0g0d4csrsto.apps.googleusercontent.com
client_secret = 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
scope = drive
team_drive =
